version:  '3'

services:
#MySQL######################################################
  mysql:
    image: mysql:5.7.22
    ports:
        - "3306:3306"
    volumes:
        - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db_laravel
      MYSQL_ROOT_PASSWORD: root

#WEB#########################################################
  web:
     build: .
     ports:
       - 8000:80
     volumes:
       - ./:/opt/data
     depends_on:
       - mysql
